Repository SCE-Development/SCE-RPC, pull requests merged in 2020-06, with the labels that each got.

#41 Correctly Format package.json
  package-lock.json
  package.json
Labels: bug, enhancement

#45 Add ESLint to Enforce Styling and Syntax
  .eslintignore
  .eslintrc.json
  client/ledsign/led_sign_client.js
  client/printing/print_client.js
  client/printing_3d/print_3d_client.js
  package-lock.json
  package.json
Labels: enhancement

#46 Add TravisCI to SCE-RPC
  .travis.yml
Labels: enhancement

#44 Add RPC Client API
  .gitignore
  .travis.yml
  client/api/2DPrinting.js
  client/api/3DPrinting.js
  client/api/LedSign.js
  client/api/SceRpcApiServer.js
  client/config/config.example.js
  client/util/logging-helpers.js
  package-lock.json
  package.json
  setup.bat
  setup.sh
  test/client/2DPrinting.js
  test/client/3DPrinting.js
  test/client/LedSign.js
  test/util/tools.js
Labels: enhancement

#47 AddMessageToQueue and ClearMessageQueue
  client/ledsign/led_sign_client.js
  client/ledsign/led_sign_grpc_pb.js
  client/ledsign/led_sign_pb.js
  proto/led_sign.proto
  server/led_sign/led_sign_pb2.py
  server/led_sign/led_sign_pb2_grpc.py
  server/led_sign/led_sign_server.py
Labels: enhancement

#48 Add Slash to Path to Prevent Server Crashing
  client/api/SceRpcApiServer.js
Labels: bug
